---
title: "Agenda"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



#### Morning session 1 
[Goodenough College](https://www.goodenough.ac.uk)[[Location](https://goo.gl/maps/cexnUGb41a4Li7hd6)]

* 09:20 - Coffees and pastries
* 09:45 - Intro: Our Research Environment (Nils Metternich) [Input](https://nilswmetternich.github.io/ResearchUCLDay/ResearchAwayDayPres2024.pdf)
* 10:00 - Celebrating (not-yet) grant successes
  + [Meg Russell](https://www.ucl.ac.uk/constitution-unit/about-us/people/professor-meg-russell)
  + [Veronika Fikfak](https://www.humanrightsnudge.com)
  + [Zeynep Bulutgil](https://www.zeynepbulutgil.com)
  + [Kate Cronin-Furman](http://www.katecroninfurman.com)
  + [Lucy Barnes](https://www.ucl.ac.uk/political-science/people/academic-teaching-and-research-staff/dr-lucy-barnes)
* 10:45 - [Breakout I](https://nilswmetternich.github.io/ResearchUCLDay/workshop1.html): The one-thing to support my grant application


#### Coffee Break (11:00)

#### Morning session 2 

* 11:15 - Ways to support your grant applications 
  + [Christian Schuster](https://www.christianschuster.net) ([Policy Lab](https://www.ucl.ac.uk/policy-lab/ucl-policy-lab))
  + [Steve Morrison](https://www.ucl.ac.uk/research/staff-students/lash-and-ioe-research-facilitation-and-coordination-team/how-we-can-help-you) Senior School Research Facilitator, LASH & IOE [Slides](https://nilswmetternich.github.io/ResearchUCLDay/morrison_pres2.pdf)
  + [Gianluca Marchiori](https://www.ucl.ac.uk/research-innovation-services/award-services/erio/european-contract-services) European Research Manager (European Research and Innovation Office)
    <!-- + [Talk resource I](https://liveuclac.sharepoint.com/sites/AH-SHSIntranet/SitePages/Joint-Faculties-Research.aspx) -->
    <!-- + [Talk resource II](https://www.ucl.ac.uk/research/support-staff/funding-ucl-research-innovation-global-engagement) -->
* 12:00 - [Breakout II](https://nilswmetternich.github.io/ResearchUCLDay/workshop2.html): Thinking about how to plan your grant applications

Read-on:

<!-- * [Resources I](https://www.research-strategy.admin.cam.ac.uk/pathwaytoimpact/index.html) -->
<!-- * [Resources II](https://www.eui.eu/Documents/MWP/AcademicCareers/ACO-conf-201819/LeveridgeBruun-UCL.pdf) -->
<!-- * [Resources III](https://www.ucl.ac.uk/research/domains/sites/research_domains/files/what-is-impact.pdf) -->
<!-- * [Resources IV](https://www.mpls.ox.ac.uk/public-engagement/top-tips/funding-pathways-to-impact-and-other-funding-schemes) -->
* [Departmental Reseach Intranet](https://liveuclac.sharepoint.com/sites/PolSciIntranet/SitePages/Research.aspx)


#### Lunch and coffees (12:30) 
[Goodenough College](https://www.goodenough.ac.uk)


#### Afternoon Sessions 
[Goodenough College](https://www.goodenough.ac.uk)

* 13:30 - Workshop I: Presentation of departmental impact strategy
  + [Presentation](https://nilswmetternich.github.io/ResearchUCLDay/alan_pres.pdf) by [Alan Renwick](https://www.ucl.ac.uk/constitution-unit/about-us/people/professor-alan-renwick)

#### Coffee Break (14:00)

* 14:15 - Inclusive research environment [Input](https://nilswmetternich.github.io/ResearchUCLDay/ResearchAwayDayPresPart2024.pdf)

Read-on:
  * [Data, measurement and empirical methods in the science of science](https://www.nature.com/articles/s41562-023-01562-4)
  * [Gender and retention patterns among U.S. faculty](https://www.science.org/doi/full/10.1126/sciadv.adi2205) 
  * [The unequal impact of parenthood in academia](https://www.science.org/doi/full/10.1126/sciadv.abd1996) 
  * [Untangling the network effects of productivity and prominence among scientists](https://www.nature.com/articles/s41467-022-32604-6)
  * [The Gender Citation Gap in International Relations](https://www.cambridge.org/core/journals/international-organization/article/gender-citation-gap-in-international-relations/3A769C5CFA7E24C32641CDB2FD03126A)
  * [Interdisciplinary researchers attain better long-term funding performance](https://www.nature.com/articles/s42005-021-00769-z)
  * [The Diversity–Innovation Paradox in Science](https://www.pnas.org/doi/full/10.1073/pnas.1915378117#sec-2)
  * [The preeminence of ethnic diversity in scientific collaboration](https://www.nature.com/articles/s41467-018-07634-8)
  * [Gender diversity leads to better science](https://www.pnas.org/doi/full/10.1073/pnas.1700616114?doi=10.1073/pnas.1700616114)

* 14:45 - Workshop II: Planning Document
  + [Vision](https://nilswmetternich.github.io/ResearchUCLDay/vision.pdf)
  + [Strategy Statement](https://nilswmetternich.github.io/ResearchUCLDay/strategy.pdf)
  + [Strategy Planning](https://nilswmetternich.github.io/ResearchUCLDay/StrategyPlanning.pdf)

Read-on:


#### Drinks (16:00) 
* Marquis Cornwallis (Buy YO)


